SELECT COUNT (ID_SERV) FROM PREST_SERV WHERE FECHA BETWEEN '01/10/18' AND '16/11/18';
SELECT COUNT (ID_SERV) FROM PREST_SERV WHERE ID_VEH IS NOT NULL;
SELECT ID_VEH FROM PREST_SERV ORDER BY ID_SERV ASC;
