--------------------------------------------------------
-- Archivo creado  - jueves-julio-09-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EMPLEADO
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."EMPLEADO" 
   (	"ID_EMP" VARCHAR2(10 BYTE), 
	"NOMBRE_EMP" VARCHAR2(50 BYTE), 
	"FECHA_ING" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.EMPLEADO
SET DEFINE OFF;
Insert into SYSTEM.EMPLEADO (ID_EMP,NOMBRE_EMP,FECHA_ING) values ('E1','Juan Perez',to_date('03/03/18','DD/MM/RR'));
Insert into SYSTEM.EMPLEADO (ID_EMP,NOMBRE_EMP,FECHA_ING) values ('E2','Manuel Piña',to_date('01/02/18','DD/MM/RR'));
Insert into SYSTEM.EMPLEADO (ID_EMP,NOMBRE_EMP,FECHA_ING) values ('E3','Jose Zapata',to_date('02/03/18','DD/MM/RR'));
Insert into SYSTEM.EMPLEADO (ID_EMP,NOMBRE_EMP,FECHA_ING) values ('E4','Ana Lopez',to_date('11/02/18','DD/MM/RR'));
Insert into SYSTEM.EMPLEADO (ID_EMP,NOMBRE_EMP,FECHA_ING) values ('E5','Luis Perez',to_date('15/03/18','DD/MM/RR'));
--------------------------------------------------------
--  DDL for Index EMPLEADO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."EMPLEADO_PK" ON "SYSTEM"."EMPLEADO" ("ID_EMP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table EMPLEADO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."EMPLEADO" ADD CONSTRAINT "EMPLEADO_PK" PRIMARY KEY ("ID_EMP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."EMPLEADO" MODIFY ("ID_EMP" NOT NULL ENABLE);
