--------------------------------------------------------
-- Archivo creado  - jueves-julio-09-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PREST_SERV
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PREST_SERV" 
   (	"ID_PRESSERV" VARCHAR2(10 BYTE), 
	"ID_SERV" VARCHAR2(10 BYTE), 
	"ID_EMP" VARCHAR2(10 BYTE), 
	"ID_VEH" VARCHAR2(10 BYTE), 
	"FECHA" DATE, 
	"SERVICIO_ID_SERV" VARCHAR2(10 BYTE), 
	"EMPLEADO_ID_EMP" VARCHAR2(10 BYTE), 
	"VEHICULO_ID_VEH" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.PREST_SERV
SET DEFINE OFF;
Insert into SYSTEM.PREST_SERV (ID_PRESSERV,ID_SERV,ID_EMP,ID_VEH,FECHA,SERVICIO_ID_SERV,EMPLEADO_ID_EMP,VEHICULO_ID_VEH) values ('PS1','S1','E1','V1',to_date('01/11/18','DD/MM/RR'),'S1','E1','V1');
Insert into SYSTEM.PREST_SERV (ID_PRESSERV,ID_SERV,ID_EMP,ID_VEH,FECHA,SERVICIO_ID_SERV,EMPLEADO_ID_EMP,VEHICULO_ID_VEH) values ('PS2','S2','E2','V2',to_date('02/11/18','DD/MM/RR'),'S2','E2','V2');
Insert into SYSTEM.PREST_SERV (ID_PRESSERV,ID_SERV,ID_EMP,ID_VEH,FECHA,SERVICIO_ID_SERV,EMPLEADO_ID_EMP,VEHICULO_ID_VEH) values ('PS3','S3','E3','V3',to_date('08/08/18','DD/MM/RR'),'S3','E3','V3');
Insert into SYSTEM.PREST_SERV (ID_PRESSERV,ID_SERV,ID_EMP,ID_VEH,FECHA,SERVICIO_ID_SERV,EMPLEADO_ID_EMP,VEHICULO_ID_VEH) values ('PS4','S4','E4','V5',to_date('08/10/18','DD/MM/RR'),'S4','E4','V5');
Insert into SYSTEM.PREST_SERV (ID_PRESSERV,ID_SERV,ID_EMP,ID_VEH,FECHA,SERVICIO_ID_SERV,EMPLEADO_ID_EMP,VEHICULO_ID_VEH) values ('PS5','S5','E5','V4',to_date('07/11/18','DD/MM/RR'),'S5','E5','V4');
--------------------------------------------------------
--  DDL for Index PREST_SERV__IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PREST_SERV__IDX" ON "SYSTEM"."PREST_SERV" ("EMPLEADO_ID_EMP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PREST_SERV_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PREST_SERV_PK" ON "SYSTEM"."PREST_SERV" ("ID_PRESSERV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PREST_SERV
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PREST_SERV" ADD CONSTRAINT "PREST_SERV_PK" PRIMARY KEY ("ID_PRESSERV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."PREST_SERV" MODIFY ("VEHICULO_ID_VEH" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PREST_SERV" MODIFY ("EMPLEADO_ID_EMP" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PREST_SERV" MODIFY ("SERVICIO_ID_SERV" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PREST_SERV" MODIFY ("ID_PRESSERV" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PREST_SERV
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PREST_SERV" ADD CONSTRAINT "PREST_SERV_EMPLEADO_FK" FOREIGN KEY ("EMPLEADO_ID_EMP")
	  REFERENCES "SYSTEM"."EMPLEADO" ("ID_EMP") ENABLE;
  ALTER TABLE "SYSTEM"."PREST_SERV" ADD CONSTRAINT "PREST_SERV_SERVICIO_FK" FOREIGN KEY ("SERVICIO_ID_SERV")
	  REFERENCES "SYSTEM"."SERVICIO" ("ID_SERV") ENABLE;
  ALTER TABLE "SYSTEM"."PREST_SERV" ADD CONSTRAINT "PREST_SERV_VEHICULO_FK" FOREIGN KEY ("VEHICULO_ID_VEH")
	  REFERENCES "SYSTEM"."VEHICULO" ("ID_VEH") ENABLE;
