--------------------------------------------------------
-- Archivo creado  - jueves-julio-09-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SERVICIO
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."SERVICIO" 
   (	"ID_SERV" VARCHAR2(10 BYTE), 
	"NOMBRE_SERV" VARCHAR2(50 BYTE), 
	"VALOR_SERV" FLOAT(126)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.SERVICIO
SET DEFINE OFF;
Insert into SYSTEM.SERVICIO (ID_SERV,NOMBRE_SERV,VALOR_SERV) values ('S1','Pintura','250000');
Insert into SYSTEM.SERVICIO (ID_SERV,NOMBRE_SERV,VALOR_SERV) values ('S2','Chapa','350000');
Insert into SYSTEM.SERVICIO (ID_SERV,NOMBRE_SERV,VALOR_SERV) values ('S3','Motor','800000');
Insert into SYSTEM.SERVICIO (ID_SERV,NOMBRE_SERV,VALOR_SERV) values ('S4','Electrico','200000');
Insert into SYSTEM.SERVICIO (ID_SERV,NOMBRE_SERV,VALOR_SERV) values ('S5','Bencina','100000');
--------------------------------------------------------
--  DDL for Index SERVICIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SERVICIO_PK" ON "SYSTEM"."SERVICIO" ("ID_SERV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table SERVICIO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."SERVICIO" ADD CONSTRAINT "SERVICIO_PK" PRIMARY KEY ("ID_SERV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."SERVICIO" MODIFY ("ID_SERV" NOT NULL ENABLE);
