--------------------------------------------------------
-- Archivo creado  - jueves-julio-09-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table VEHICULO
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."VEHICULO" 
   (	"ID_VEH" VARCHAR2(10 BYTE), 
	"MARCA" VARCHAR2(50 BYTE), 
	"MODELO" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.VEHICULO
SET DEFINE OFF;
Insert into SYSTEM.VEHICULO (ID_VEH,MARCA,MODELO) values ('V1','Fiat','600');
Insert into SYSTEM.VEHICULO (ID_VEH,MARCA,MODELO) values ('V2','Nissan','sentra');
Insert into SYSTEM.VEHICULO (ID_VEH,MARCA,MODELO) values ('V3','Opel','corsa');
Insert into SYSTEM.VEHICULO (ID_VEH,MARCA,MODELO) values ('V4','Ford','fiesta');
Insert into SYSTEM.VEHICULO (ID_VEH,MARCA,MODELO) values ('V5','Kia','rio');
--------------------------------------------------------
--  DDL for Index VEHICULO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."VEHICULO_PK" ON "SYSTEM"."VEHICULO" ("ID_VEH") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table VEHICULO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."VEHICULO" ADD CONSTRAINT "VEHICULO_PK" PRIMARY KEY ("ID_VEH")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."VEHICULO" MODIFY ("ID_VEH" NOT NULL ENABLE);
